# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 412009100fc073ec840e545921f5861785f4b5c9f180da89594b61ab3198ab0e920b089055f503ec01ea6111f7a65372bb508e3348bc91c7a9b1aac6cd128fdf

test:
  secret_key_base: 9179eec2c670df7a1d9519c2ced69be8a6285ef69987ccee21cb05062da6483c66e8ab24279f3ac9af37dd39c834805ffc62852ac877664363545aece698f8ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
